from __future__ import annotations

import html
from datetime import datetime
from typing import Iterable, Optional

from models import JobPosting


def render_jobs_email(
    *,
    subject_title: str,
    run_at: datetime,
    new_jobs: list[JobPosting],
    all_jobs: Optional[list[JobPosting]] = None,
    failures: Optional[list[dict[str, str]]] = None,
) -> tuple[str, str]:
    subject = subject_title
    header = f"<h2 style='margin:0 0 8px 0'>{html.escape(subject_title)}</h2>"
    meta = f"<div style='color:#667085;font-size:13px;margin-bottom:16px'>Run: {run_at.strftime('%Y-%m-%d %H:%M')}</div>"

    if not new_jobs and not (all_jobs or []):
        body = (
            f"{header}{meta}"
            "<div style='font-size:14px;color:#101828'>No matching postings found today.</div>"
        )
        return subject, _wrap_email(body)

    sections: list[str] = [header, meta]

    if new_jobs:
        sections.append("<h3 style='margin:16px 0 8px 0'>New postings</h3>")
        sections.append(_render_jobs_table(new_jobs))
    else:
        sections.append(
            "<div style='font-size:14px;color:#101828;margin:12px 0'>No new postings since last run.</div>"
        )

    if all_jobs is not None:
        sections.append("<h3 style='margin:20px 0 8px 0'>All matching postings</h3>")
        sections.append(_render_jobs_table(all_jobs))

    if failures:
        sections.append("<h3 style='margin:20px 0 8px 0'>Scrape failures</h3>")
        sections.append(_render_failures(failures))

    return subject, _wrap_email("".join(sections))


def _render_jobs_table(jobs: list[JobPosting]) -> str:
    rows = []
    for j in jobs:
        posted = j.date_posted.isoformat() if j.date_posted else ""
        rows.append(
            "<tr>"
            f"<td>{html.escape(j.hospital)}</td>"
            f"<td>{html.escape(j.job_title)}</td>"
            f"<td>{html.escape(j.location or '')}</td>"
            f"<td>{html.escape(posted)}</td>"
            f"<td>{html.escape(j.job_type)}</td>"
            f"<td><a href='{html.escape(j.url)}' style='color:#175CD3'>View</a></td>"
            "</tr>"
        )

    return (
        "<table style='width:100%;border-collapse:collapse;font-size:13px'>"
        "<thead>"
        "<tr style='background:#F2F4F7'>"
        "<th style='text-align:left;padding:10px;border:1px solid #EAECF0'>Hospital</th>"
        "<th style='text-align:left;padding:10px;border:1px solid #EAECF0'>Title</th>"
        "<th style='text-align:left;padding:10px;border:1px solid #EAECF0'>Location</th>"
        "<th style='text-align:left;padding:10px;border:1px solid #EAECF0'>Posted</th>"
        "<th style='text-align:left;padding:10px;border:1px solid #EAECF0'>Type</th>"
        "<th style='text-align:left;padding:10px;border:1px solid #EAECF0'>Link</th>"
        "</tr>"
        "</thead>"
        "<tbody>"
        + "".join(rows)
        + "</tbody></table>"
    )


def _wrap_email(inner_html: str) -> str:
    return (
        "<div style='font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif;"
        "max-width:860px;margin:0 auto;padding:18px;color:#101828'>"
        f"{inner_html}"
        "<div style='margin-top:18px;font-size:12px;color:#667085'>Generated by nurseTracker.</div>"
        "</div>"
    )


def _render_failures(failures: list[dict[str, str]]) -> str:
    items = []
    for f in failures:
        hospital = html.escape(str(f.get("hospital") or ""))
        error = html.escape(str(f.get("error") or ""))
        if not hospital and not error:
            continue
        items.append(f"<li><b>{hospital}</b>: {error}</li>")
    if not items:
        return "<div style='font-size:13px;color:#101828'>None.</div>"
    return "<ul style='margin:0;padding-left:20px;color:#101828;font-size:13px'>" + "".join(items) + "</ul>"
